### ISSUE TITLE
enhancer regions

### ISSUE THREAD

**Issue by liyangyang12** [vanheeringen-lab/ANANSE#181]
Hi,
Can user-provided enhancer regions contain promotor regions? Why not train the enhancer region and the promotor region together when training the model?

Thanks a lot for your time and effort!

**Comment by siebrenf** [comment]
> Can user-provided enhancer regions contain promotor regions?

Yes! If you wish, you can even remove promoters during ANANSE network with the `--exclude-promoter` flag.

> Why not train the enhancer region and the promotor region together when training the model?

Unless I'm mistaken, they are trained together!

**Comment by liyangyang12** [comment]
Thanks!
But in development version, I noticed that the calculation of distance weight in Inference of "gene regulatory networks" didn't consider the promotor regions in 2kb?
![1651929603(1)](https://user-images.githubusercontent.com/43978418/167256153-22e0b935-6bb8-40a2-a409-b81eb491098a.png)

By the way, do you recommend using ANANSE for non-model organisms?

Thanks a lot for your time and effort!

**Comment by siebrenf** [comment]
I double checked the code to be sure :) Starting from version 0.2, we include both promoters and enhancers by default (with the option to exclude them). So that picture is outdated, thank you for pointing that out!

We have done several analyses with non-model organisms, which did show promising results! I highly recommend using the development branch for this. Which files you need, and how to prepare them, can be found on the [input data](https://anansepy.readthedocs.io/en/develop/input_data/) page.

Good luck!

**Comment by liyangyang12** [comment]
OK, Thank you very much!
